feat: Process Chain XSD
intershop/intershop.github.io pull request #6
Opened 2023-05-31 14:14 UTC by DevDavido

- Added processchain.xsd
- Added XML schema links to README
- Added .gitignore

2023-05-31 14:19 UTC, stefanh1 approved these changes

2023-06-04 10:35 UTC, Thomas-Bergmann requested changes

2023-06-04 10:35 UTC, Thomas-Bergmann commented on xml/enfinity/6.5/core/processchain.xsd
> +    targetNamespace="https://intershop.github.io/xml/enfinity/6.5/core/processchain"
the targetNamespace must be not changed.

2023-06-04 10:37 UTC, Thomas-Bergmann commented on xml/enfinity/6.5/core/processchain.xsd
> +    targetNamespace="https://intershop.github.io/xml/enfinity/6.5/core/processchain"
I would prefer to create a new version for processchain.xsd in a new location, which contains the new state.

2023-06-05 09:09 UTC, DevDavido commented
Closing this PR, see PR #7 instead.

2023-06-05 09:09 UTC, closed without merging