Improve readme
intershop/intershop.github.io pull request #9
Opened 2023-12-13 16:39 UTC by marschmidt89

I've reworked the readme file here a bit. 

I basically added an introduction and some more descriptions, removed one outdated link from the table and added a link to more information in the Knowledge Base.

2023-12-14 07:50 UTC, skiesewetter-intershop approved these changes

2023-12-14 08:01 UTC, DevDavido requested changes

2023-12-14 08:01 UTC, DevDavido commented on README.md
> +This repository contains XSD (XML Schema Definition) files that facilitate the creation of XML files for defining process chains. Process chains are a mechanism for automating the sequential executio
This repository is not only intended for process chain XSDs alone, but rather all ICM related XSDs in the future.

2023-12-14 08:01 UTC, DevDavido commented on README.md
> +Newer versions of the XSD files follow semantic versioning principles. Each XSD file's namespace specifies its version.
May be reworded to "Newer versions of the XSD files including the `semantic` keyword"

2024-01-08 07:59 UTC, DevDavido commented on README.md
> +This repository contains XSD (XML Schema Definition) files that facilitate the creation of XML files for defining process chains. Process chains are a mechanism for automating the sequential executio
/cc @marschmidt89

2024-01-16 13:25 UTC, DevDavido approved these changes

2024-01-16 13:26 UTC, merged